'use strict';
// One help catalog covers static controls and controls created by live dialogs.
(()=>{
 const help={
  tournamentPicker:'Choose the tournament to inspect. Switching tournaments does not stop running games.',
  start:'Start or resume this tournament. Completed results remain saved; unfinished games restart from their recorded openings. Other started tournaments wait in the worker queue.',
  pause:'Stop scheduling new games and let the active games finish. The tournament becomes paused when they have drained.',
  cancel:'Stop the active games now. Their unfinished attempts are archived separately, and the games can restart from the same openings.',
  deleteTournament:'Permanently remove the selected tournament and its data after a named confirmation. All tournaments and experiments must be stopped or drained first.',
  newTournament:'Create a paused tournament from the profiles selected in Engine library, or the entire library if that option is enabled.',
  exportPgn:'Choose compact, tagged, moves-only or archive PGN, select measurements, and save official results to your chosen file. Recorded opening moves are included; all original attempts remain saved.',
  exportStats:'Export the selected tournament’s current standings as CSV.',exportStatsJson:'Export current standings and statistical data as JSON.',
  tournamentReport:'Preview and save a self-contained HTML report of the committed tournament results.',
  openingReport:'Compare official results by opening and color, with an optional engine perspective.',poolRatings:'Fit ratings against a fixed reference engine, using the current official comparisons in the pool.',crossTable:'Compare each row engine against each column engine. Select a cell for detailed statistics.',pairingReview:'Review pairings, resolve blocked rounds and record explicit advancement or rematch decisions.',
  boardCount:'Choose how many live thumbnails to render, up to 128. Scroll inside Live boards to reach further games. This display setting does not limit games or participants.',
  flipBoards:'Rotate the displayed chessboards. Game positions and results do not change.',focusPicker:'Choose a live game. The focused board, Engine search panel and following graphs share this selection.',
  confidenceMethod:'Choose how intervals are calculated at the selected confidence level. Normal intervals can be unreliable in small samples; conservative Hoeffding bounds are wider. Neither is a sequential stopping rule.',
  gameFilter:'Filter stored games by state or failure classification. An interrupted game may already have a later successful attempt.',
  replayMode:'Diagnostic replay keeps the official result. Replacement makes the new attempt official and recalculates results without double-counting. Affected later rounds require an explicit dependency decision.',
  replaySelected:'Queue the checked games using the chosen replay mode. Pause and drain this tournament before changing attempts.',
  replayAll:'Queue every game matching the selected failure filter, including games beyond the current page.',selectGames:'Select or clear the games on this visible page. This does not select unseen pages.',
  gameNumber:'Enter a one-based game number to open its saved attempts directly, without paging through the history.',findGame:'Open the saved history for the game number entered here. The game must have been materialized by the scheduler.',
  engineSearch:'Search registered engine profile names. Only a page of matching profiles is displayed.',addEngine:'Select a UCI engine executable and configure its options, resources and optional independent time control.',emptyAdd:'Add a UCI engine executable to the engine library.',
  scanFolder:'Discover UCI engines in a chosen folder. Unknown executables are started one at a time.',cloneEngine:'Create editable copies of the checked engine profiles.',bulkEngine:'Apply common Threads and Hash values to checked library profiles. Existing tournaments keep their original snapshots.',importEngines:'Import engine profiles from a JSON file. Executable paths must be valid on this computer before play.',exportEngines:'Save registered engine profiles and their settings as JSON.',allProfiles:'Use every registered profile in the next tournament, including profiles on other pages. Concurrency remains a separate setting.',
  epath:'Path to the engine executable. Test connection checks that it speaks UCI; Save profile stores the configuration.',ename:'Your label for this engine configuration. Leave blank to use the discovered engine name.',eargs:'Optional command-line arguments passed to the engine. Quote paths that contain spaces.',ecwd:'Folder the engine starts in. Leave blank to use the executable’s folder; useful for relative network and configuration paths.',ethreads:'CPU threads requested per engine process. The matching advertised UCI Threads option stays synchronized.',ehash:'Hash table memory in MB for each engine process. The matching UCI Hash option stays synchronized.',eaffinity:'Optional logical CPU numbers, separated by commas, such as 0,2,4. Leave blank to let Windows schedule the engine.',egpu:'Name for a shared GPU resource group. Tournament group limits control how many engine processes can use it at once.',eextra:'Estimated memory in MB beyond the hash table, per engine process. Used when admitting games to the resource budget.',eindependent:'Give this engine its own time, node or depth control. Otherwise it uses the tournament default. This enables handicap comparisons.',testEngine:'Launch the engine, read its identity and UCI options, then close it. The library is updated only when you choose Save profile.',saveEngine:'Save this engine configuration in the library. Existing tournaments keep their recorded profile snapshots.',bulkThreads:'Threads to request for each selected engine profile.',bulkHash:'Hash memory in MB per selected engine process.',applyBulk:'Save these resource values to the selected library profiles and their advertised UCI options.',
  tname:'Name used in the tournament list and saved PGN metadata.',tformat:'Select the competition format. A head-to-head match or SPRT requires exactly two profiles; other formats define their own pairings.',tcycles:'Number of opening cycles per matchup. With reversed colors enabled, each cycle contains two games.',trounds:'Number of rounds for Swiss or ladder tournaments.',tcandidates:'For a gauntlet, the first selected profiles are candidates and play against the remaining opponents.',tpaired:'Play each selected opening twice with engine colors reversed. Paired statistics update after both legs finish.',tpreset:'Copy saved time, resource and pairing conditions into this new tournament. Engine-specific time controls still take precedence.',
  tconcurrency:'Maximum number of games running at once. Each game uses two engine processes. Participant count and total scheduled games are independent of this limit.',tcpu:'Combined engine thread budget. Zero uses the detected hardware; concurrency and memory limits still apply.',tmemory:'Memory admission budget in MB. Zero uses an automatic estimate of available memory. Hash and additional profile memory count toward this budget.',tgpu:'Concurrent engine-process slots for named GPU groups, for example gpu0:2,gpu1:1.',tponder:'Allow engines to think during the opponent’s turn. Admission budgets both engines’ resources.',
  tretries:'Maximum automatic replacement retries per failed game. Zero disables automatic retries. Every attempt is retained.',tstartup:'Seconds allowed for the engine to acknowledge UCI during startup. This watchdog is separate from the chess clock.',tready:'Seconds allowed for the engine’s readyok response. This watchdog is separate from the chess clock.',thang:'Maximum time to wait for a search before classifying it as a hang. Applies even to node/depth tests and is separate from chess-clock limits.',tstop:'Seconds allowed for an engine to respond to stop before cleanup escalates.',ttolerance:'Extra seconds allowed when enforcing a clock limit, to account for communication and scheduling latency.',toverhead:'Seconds charged to the engine on every move in addition to measured search time.',
  topeningSource:'Start from the normal position, an opening file/book, a saved position, or all 960 Chess960 starts.',tsavedPosition:'Copy a saved position into this tournament. Later edits to the position library do not change this tournament.',topening:'Path to a PGN, EPD, FEN or Polyglot opening file. Both legs of a paired game use the same recorded opening.',tdepth:'Maximum opening-book depth in plies; one ply is one move by one side.',tseed:'Seed used for reproducible opening selection and randomized seeding.',torder:'Cycle through openings in order, or choose them using the recorded random seed.',tfile960:'Interpret openings with Chess960 castling rules. The selected engines must advertise Chess960 support.',t960:'Use all 960 legal Chess960 starting positions.',
  tmaxplies:'End a game as an adjudicated draw after this many plies. Zero disables the cap; one ply is one move by one side.',tannotations:'Include available move evaluations, depth, nodes and clocks in saved game annotations.',tclaim:'Allow the referee to claim threefold-repetition and fifty-move draws when the conditions hold.',tresign:'Evaluation threshold in centipawns for resignation adjudication; zero disables it. The threshold must persist for the configured consecutive-ply window.',tdraw:'Maximum absolute evaluation in centipawns for draw adjudication; zero disables it. Minimum game length and consecutive-ply requirements also apply.',tsyzygy:'Optional tablebase folder for the independent referee. Engine tablebase options are configured separately.',telo0:'SPRT null hypothesis: Elo difference to test against, from the first engine’s perspective.',telo1:'SPRT alternative hypothesis: Elo difference above H0. The paired sequential test uses alpha and beta of 0.05.',
  fseeding:'Use selected-engine order or shuffle deterministically using the tournament seed.',fbye:'Tournament points awarded per scheduled bye game. Byes never count as played or rated games.',frematches:'Permit Swiss rematches automatically when needed. Otherwise the tournament pauses for an explicit pairing decision.',fknockout:'Choose how a tied knockout matchup is resolved: ranking tiebreak, extra games or a manual winner.',fplayoffLimit:'Maximum additional playoff stages before using the configured fallback.',fplayoffCycles:'Opening cycles played in each extra playoff stage; the tournament’s color-pair policy still applies.',ffallback:'Choose what happens if every allowed playoff stage is tied.',fdistance:'Number of ladder positions between challenger and opponent.',fmovement:'After a successful challenge, swap the two players or move the challenger up and shift the intervening players.',createTournament:'Save a paused tournament with the total shown below. Review it before choosing Start / resume.',useRecommended:'Use the concurrency suggested by the selected profiles and available CPU, memory and GPU budgets.',
  pieceChoice:'Select the chess-piece design used on all boards. Preview it here, then choose Apply appearance.',displayTheme:'Choose a dark Midnight interface or a light Daylight interface.',displayFontSize:'Base text size from 12 to 24 pixels. Controls scale with it; the setting is saved for this workspace.',squareLight:'Color of the board’s light squares.',squareDark:'Color of the board’s dark squares.',applyDisplay:'Save the selected design, colors, font and visible panels. Changes persist after restarting the program.',importPieces:'Import 12 self-contained SVG files named wK.svg through wP.svg and bK.svg through bP.svg. External content and scripts are rejected.',layoutName:'Name for the current panel arrangement, sizes and graph selections.',layoutChoice:'Select a previously saved workspace arrangement.',saveLayout:'Save the current panel arrangement under the entered name.',loadLayout:'Restore the selected layout’s panel positions, sizes and graphs.',resetLayout:'Restore the default panel sizes and columns, with the focused game visible. Tournament data is unchanged.',theme:'Switch between light and dark themes and save the choice.',
  savePreset:'Create reusable test conditions for future tournaments.',presetName:'Name of this reusable preset. Saving under a new name keeps the original.',pThreads:'CPU threads requested per engine when the preset is applied.',pHash:'Hash table memory in MB per engine when the preset is applied.',pPaired:'Apply reversed-color opening pairs by default.',pPonder:'Apply pondering by default. Both engines’ resources are budgeted.',saveP:'Save these reusable conditions. Existing tournaments retain their recorded settings.',
  newPosition:'Set up and save an opening position using a board or FEN.',positionName:'Name used to select this position in tournament setup.',positionFen:'FEN describes the board, side to move, castling rights, en passant square and move counters.',setup960:'Use Chess960 rules for this position.',setup960Index:'Chess960 starting-position index, from 0 to 959.',setupGenerate:'Replace the setup board with the chosen Chess960 starting position.',setupInitial:'Reset the setup board to the normal chess starting position.',setupClear:'Clear the setup board so you can place pieces. The position must be legal before saving.',setupFlip:'Rotate the setup board without changing the position.',setupTurn:'Side whose turn it is to move from this position.',setupCastle:'Castling rights in FEN notation. Use a dash if neither side may castle.',setupEp:'En passant target square in FEN notation, or a dash if none.',setupHalf:'Halfmove clock: plies since the last pawn move or capture.',setupFull:'Full move number in the FEN, starting at 1.',savePosition:'Validate and save this starting position. New tournaments can copy it into their recorded openings.',
  newSuite:'Create an EPD best/avoid-move accuracy suite for the selected library profiles.',newBenchmark:'Compare repeatable searches across thread counts using the selected library profiles.',refreshExperiments:'Refresh queued experiments and their progress.',exname:'Name of this suite or benchmark.',expath:'EPD file containing best-move (bm) or avoid-move (am) operations.',exthreads:'Positive integer thread counts to compare, separated by commas, for example 1,2,4,8.',exrepeats:'Number of repeated searches per engine and thread count.',exfen:'Legal FEN position used for every benchmark search.',createExperiment:'Save a paused experiment. Start it from the experiment list; it runs after queued tournaments.',exportExperiment:'Export the recorded experiment settings and results as JSON.',cancelExperiment:'Stop the current experiment case and archive its interrupted attempt.',
  attemptPicker:'Choose a recorded attempt. The OFFICIAL label identifies the result currently used in standings.',replayFirst:'Go to the recorded opening position.',replayBack:'Step back one saved ply.',replayForward:'Step forward one saved ply.',replayLast:'Go to the last saved move in this attempt.',graphMetric:'Choose the recorded move measurement plotted below. Missing engine-reported fields remain unavailable.',
  addGraph:'Add a graph for a live game, recorded game, tournament trend or system resources.',graphKind:'Choose the measurement to display. Some metrics depend on engine-reported telemetry.',graphGame:'Follow the focused live game or a specific recorded game number.',graphNumber:'One-based recorded game number whose latest attempt supplies the graph.',graphEngineSearch:'Find the tournament participant whose perspective the trend should use.',graphEngine:'Engine perspective used for the tournament trend.',graphCi:'Confidence-interval method for the Elo trend. Repeated viewing is not a statistical stopping rule.',saveGraph:'Add or update this graph and save it in the workspace.',
  reportSearch:'Search participants to choose the perspective for opening/color results.',reportProfile:'Use White across the tournament or the chosen engine as the score perspective.',downloadOpeningCsv:'Export all official opening rows for the chosen perspective, including rows beyond this page.',saveTournamentReport:'Save the currently selected tournament’s committed results as a self-contained HTML report.',
  anchorSearch:'Search the tournament’s engines for a fixed rating reference.',anchorEngine:'The reference engine whose rating is held fixed in the pool fit.',anchorRating:'Numerical rating assigned to the reference engine. This establishes the scale and is not an inferred absolute rating.',saveAnchor:'Save this reference and recalculate connected pool ratings from current official results.',ratingSearch:'Filter displayed rating rows by engine name.',ratingCsv:'Export all pool-rating rows as CSV.',ratingJson:'Export all pool-rating rows and model information as JSON.',crossSearch:'Filter participants on both axes of the crosstable.',h2hSearch:'Find an opponent for the selected engine’s head-to-head results.',
  refreshPairings:'Refresh the recorded round, pairing conflicts and advancement decisions.',approveRematches:'Explicitly allow rematches for the blocked Swiss round. The decision is saved in the audit history.',manualPairs:'Enter participant-number pairs in the format shown here. Each eligible participant must appear exactly once, either in a pair or as a bye.',manualByes:'Comma-separated participant numbers receiving byes in this manual round.',saveManualRound:'Validate and save the manual pairings and byes for the blocked round.',winner:'Choose the engine that advances from this tied matchup. The decision is recorded.',
  retrySaving:'After resolving a storage problem, verify PGN saving, recover unfinished attempts and retry backup/cleanup. Stop active games and experiments first.',keepTournament:'Close this confirmation and keep the tournament.',confirmDeleteTournament:'Permanently delete this named tournament, its attempts/settings and automatic PGN/backup records. Other tournaments, library profiles and external exports are kept.'
 };
 const tcHelp={kind:'Choose a chess-clock, fixed move-time, depth or pure node limit. Node-only mode sends go nodes N with no chess-clock limit.',seconds:'Initial time in seconds for a chess-clock control, or the time allowed for each move in fixed move-time mode.',increment:'Seconds added after a completed move.',delay:'Free seconds allowed for each move before time is charged to the bank.',nodes:'Positive integer node budget for each move. No chess-clock limit is sent; the separate hang watchdog still applies.',depth:'Search-depth limit in plies. No chess-clock limit is sent; the hang watchdog still applies.',repeat:'Repeat the last stage after its move count is reached. A repeating stage must have a positive move count.'};
 const optionHelp={nodes:'Pure nodes per move: sends go nodes N, with no chess-clock limit.',depth:'Stop searching at the specified depth, with the separate hang watchdog still enabled.',movetime:'Allow a fixed amount of search time on each move.',sudden_death:'One time bank for the entire game, without increment.',fischer:'Add the chosen increment after each completed move.',delay:'Charge the time bank only after the per-move delay is used.',bronstein:'Refund up to the chosen delay each move; time beyond the delay is charged.',staged:'Use multiple move-count stages, optionally repeating the final stage.',diagnostic:'Preserve the official result and save a separate diagnostic attempt.',replacement:'Use the new attempt as the official result and recompute standings and paired statistics.',match:'Two engine profiles play repeated openings.',round_robin:'Every participant plays every other participant.',gauntlet:'The selected candidate group plays the remaining opponents.',self_play:'Each engine plays itself; no between-engine Elo inference is made.',swiss:'Pair similarly scoring engines in successive rounds, with recorded rematch and bye policies.',knockout:'A single loss eliminates an engine from the bracket.',double_elimination:'Two losses eliminate an engine; a final reset may be necessary.',ladder:'Engines challenge other ladder positions under the selected movement rule.',sprt:'Sequential two-engine comparison with recorded hypothesis boundaries.'};
 const selector='button,input:not([type=hidden]),select,textarea,summary,[data-help],[role=separator],tr[data-slot],tr[data-game],[data-livegame]';
 function label(el){return (el.getAttribute('aria-label')||el.labels?.[0]?.textContent||el.closest('.field,.option')?.querySelector('label')?.textContent||el.placeholder||(el.matches('button,summary')?el.textContent:'')||el.id||'Control').replace(/\s+/g,' ').trim()}
 function describe(el){
  if(el.dataset.help)return el.dataset.help;
  if(help[el.id])return help[el.id];
  if(el.hasAttribute('data-slot'))return 'Open live head-to-head comparisons from this engine’s perspective.';
  if(el.hasAttribute('data-game')||el.hasAttribute('data-livegame'))return 'Open this game’s saved attempts, move replay, clocks and diagnostic logs.';
  if(el.dataset.tc)return tcHelp[el.dataset.tc];
  if(el.dataset.stage)return {moves:'Moves in this stage. Zero means final sudden death and cannot be used in a repeating stage.',seconds:'Seconds added to the time bank when this stage begins.',increment:'Seconds added after each completed move during this stage.'}[el.dataset.stage];
  const option=el.closest('[data-option]');if(option){const range=option.querySelector('small')?.textContent||'';return 'Engine-provided UCI option “'+option.dataset.option+'”. '+range+'. '+(option.dataset.type==='button'?'When selected, this command is sent when the engine connects.':'Saved per profile; existing tournaments keep their recorded value.')}
  if(el.hasAttribute('data-tiebreak'))return 'Ranking criterion in this priority position. Tied scores proceed through the chosen criteria; initial seed is the deterministic fallback.';
  if(el.hasAttribute('data-showpanel'))return 'Show or hide the '+label(el)+' panel. Hidden panels do not stop running games or change saved results.';
  if(el.hasAttribute('data-browse'))return el.dataset.folder==='true'?'Choose a folder using the native folder picker.':'Choose a file using the native file picker.';
  const dynamic={engine:'Select this engine profile for the next tournament or experiment.',edit:'Configure this registered engine profile.',gamecheck:'Select this game for a diagnostic or replacement replay.',ply:'Show the saved board and clocks after this move.',comparison:'Open detailed head-to-head statistics for these two engines.',editPreset:'Edit these reusable conditions. Existing tournaments remain unchanged.',copyPreset:'Create a separate copy of these reusable conditions.',editPosition:'Edit this saved starting position.',exportPosition:'Save this position as FEN.',exstart:'Start or resume this experiment after queued tournaments.',expause:'Stop scheduling new experiment cases and let the current case finish.',exresults:'Inspect recorded cases, accuracy, timings and failures.',graphSettings:'Change this graph’s metric, game source or engine perspective.',graphSvg:'Export this graph as a scalable SVG image.',graphCsv:'Export this graph’s displayed series as CSV.',graphRemove:'Remove this graph from the workspace. Saved tournament data is unchanged.'};
  for(const key in dynamic)if(key in el.dataset)return dynamic[key];
  if(el.classList.contains('add-stage'))return 'Add another time-control stage. Stages are played in the displayed order.';
  if(el.classList.contains('remove-stage'))return 'Remove this stage from the time control being edited.';
  if(el.classList.contains('dock-handle'))return 'Drag this panel by its handle to reorder it or move it between workspace columns.';
  if(el.getAttribute('role')==='separator')return 'Drag to resize the workspace columns. When focused, use the left and right arrow keys.';
  if(el.matches('[data-close]'))return 'Close this window. Unsaved form edits are discarded; running games continue.';
  if(/Prev$/.test(el.id))return 'Show the previous page. Records on other pages remain saved.';
  if(/Next$/.test(el.id))return 'Show the next page. Paging does not affect running games.';
  if(el.id==='gamesFirst')return 'Jump to the first page of the current game filter.';
  if(el.id==='gamesLast')return 'Jump to the last page of the current game filter.';
  if(el.classList.contains('nav'))return 'Open '+label(el).replace(/^[^\p{L}]+/u,'')+'. Running tests continue in the worker.';
  if(el.closest('.piece-palette'))return 'Choose this piece, then select a square on the setup board to place it. Choose Erase to remove a piece.';
  if(el.title)return el.title;
  if(el.textContent?.includes('Display & layout'))return 'Choose chess pieces, board colors, text size and saved panel layouts.';
  return el.matches('select')?'Choose '+label(el).toLowerCase()+'.':el.matches('input,textarea')?'Enter '+label(el).toLowerCase()+'.':'Open or apply '+label(el).toLowerCase()+'.';
 }
 function decorate(root){
  const controls=[...(root.matches?.(selector)?[root]:[]),...root.querySelectorAll(selector)];
  for(const el of controls){if(el.closest('.hover-help'))continue;const text=describe(el);if(!text)continue;el.dataset.help=text;
   if(el.matches('tr[data-slot],tr[data-game],[data-livegame]'))el.tabIndex=0;
   if(el.matches('[data-close]'))el.setAttribute('aria-label','Close');
   if(el.title==='Hide panel')el.setAttribute('aria-label','Hide '+(el.closest('.panel')?.querySelector('h2')?.textContent||'panel'));
   if(el.matches('input,select,textarea')&&!el.labels?.length&&!el.hasAttribute('aria-label'))el.setAttribute('aria-label',label(el));
   if(el.matches('select'))for(const o of el.options)if(optionHelp[o.value])o.title=optionHelp[o.value];
  }
 }
 decorate(document.documentElement);
 const observer=new MutationObserver(records=>{for(const r of records)for(const n of r.addedNodes)if(n.nodeType===1&&!n.matches('svg,path,img,.square,.hover-help')&&!n.closest('.hover-help'))decorate(n)});
 observer.observe(document.body,{childList:true,subtree:true});
 const tooltip=document.createElement('div');tooltip.id='controlHelp';tooltip.className='hover-help';tooltip.setAttribute('role','tooltip');tooltip.setAttribute('popover','manual');tooltip.style.margin='0';document.body.append(tooltip);
 let target,timer,previousDescription;
 function hide(){clearTimeout(timer);if(target){if(previousDescription)target.setAttribute('aria-describedby',previousDescription);else target.removeAttribute('aria-describedby')}target=null;previousDescription=null;if(tooltip.matches(':popover-open'))tooltip.hidePopover();tooltip.hidden=true}
 function show(el){hide();target=el;previousDescription=el.getAttribute('aria-describedby');timer=setTimeout(()=>{if(!target?.isConnected)return;const text=describe(target);if(!text)return;tooltip.textContent=text;tooltip.hidden=false;tooltip.showPopover();target.setAttribute('aria-describedby',[previousDescription,'controlHelp'].filter(Boolean).join(' '));const rect=target.getBoundingClientRect(),size=tooltip.getBoundingClientRect();tooltip.style.left=Math.max(12,Math.min(rect.left,innerWidth-size.width-12))+'px';tooltip.style.top=(rect.bottom+10+size.height<innerHeight?rect.bottom+10:Math.max(12,rect.top-size.height-10))+'px';},350)}
 document.addEventListener('pointerover',e=>{const el=e.target.closest(selector);if(el&&el!==target)show(el)});
 document.addEventListener('pointerout',e=>{if(target&&!target.contains(e.relatedTarget))hide()});
 document.addEventListener('focusin',e=>{const el=e.target.closest(selector);if(el)show(el)});
 document.addEventListener('focusout',hide);document.addEventListener('pointerdown',hide);document.addEventListener('scroll',hide,true);document.addEventListener('keydown',e=>{if(e.key==='Escape')hide()});
 document.addEventListener('keydown',e=>{if(e.target.matches('tr[data-slot],tr[data-game],[data-livegame]')&&['Enter',' '].includes(e.key)){e.preventDefault();e.target.click()}});
})();
