'use strict';

function backupHealth(backup){
 if(!backup)return '';
 const labels={waiting:'Waiting for first recovery copy',copying:'Creating recovery copy',verifying:'Checking recovery copy',flushing:'Finishing backup on disk',ready:'Verified recovery copy ready',error:'Recovery backup needs attention'};
 const busy=['copying','verifying','flushing'].includes(backup.phase);
 const size=ArenaFormat.bytes;
 return `<section class="backup-health" aria-label="Recovery backup"><div class="backup-heading"><h3>${labels[backup.phase]||'Recovery backup'}</h3>${backup.completed_at?`<span>Last verified ${new Date(backup.completed_at*1000).toLocaleString()}</span>`:''}</div>${busy?`<progress max="100" ${backup.percent==null?'':`value="${backup.percent}"`} aria-label="Recovery copy progress"></progress><p>${backup.percent==null?'Verification and disk flush finish before the copy is rotated into the backup set.':fmt(backup.percent)+'% copied; verification follows.'}</p>`:''}${backup.size_bytes?`<div class="backup-details"><span><b>${size(backup.size_bytes)}</b> latest copy</span><span><b>${backup.backup_count} / 5</b> rotating copies</span><span><b>${size(backup.total_bytes)}</b> backup storage</span></div>`:''}<p class="caption">Moves and results commit as play continues. Unchanged copies are reused; large-copy intervals adapt from 1 to 15 minutes to reduce disk work. The final backup includes all committed changes before the app closes.</p></section>`;
}

// Keep report and comparison controls discoverable from the keyboard.
const reviewLabels={standPrev:'Previous standings page',standNext:'Next standings page',engPrev:'Previous engines page',engNext:'Next engines page',gamesPrev:'Previous games page',gamesNext:'Next games page',gamesFirst:'First games page',gamesLast:'Last games page',flipBoards:'Flip all live boards',crossRowPrev:'Previous crosstable rows',crossRowNext:'Next crosstable rows',crossColumnPrev:'Previous crosstable columns',crossColumnNext:'Next crosstable columns',openingPrev:'Previous openings page',openingNext:'Next openings page',ratingPrev:'Previous ratings page',ratingNext:'Next ratings page',h2hPrev:'Previous opponents page',h2hNext:'Next opponents page',replayFirst:'Go to opening position',replayBack:'Previous move',replayForward:'Next move',replayLast:'Go to final move'};
function labelReviewControls(root){
 for(const [id,label] of Object.entries(reviewLabels)){const control=root.querySelector('#'+id);if(control)control.setAttribute('aria-label',label)}
 for(const table of root.querySelectorAll('.table-scroll')){table.tabIndex=0;table.setAttribute('role','region');if(!table.hasAttribute('aria-label'))table.setAttribute('aria-label','Scrollable results table')}
}
labelReviewControls(document);
new MutationObserver(()=>labelReviewControls($('#modal'))).observe($('#modalContent'),{childList:true,subtree:true});

const guideButton=document.createElement('button');guideButton.className='subtle';guideButton.textContent='Getting started & feedback';$('.side-bottom').append(guideButton);
guideButton.onclick=()=>modal('Getting started · 0.2.0 Beta 2',`<div class="tester-intro"><span class="pill">FRIENDLY TESTING BUILD</span><h3>A reproducible test in three steps</h3><ol><li><b>Add engines.</b> In Engine library, add executables and test their UCI connection. Save each profile, then select the profiles you want to compare.</li><li><b>Choose conditions.</b> Create a tournament, review its opening policy, scheduled games, time control and concurrency. It starts paused so you can review it.</li><li><b>Run and review.</b> Start / resume begins play. Pause & drain finishes current games. Results & exports contains the reports and the official PGN Save As option.</li></ol><h3>Reading the results</h3><p>Score includes wins plus half of draws. Paired Elo and confidence intervals use complete color-reversed pairs, so they can update later than W–D–L. “—” means unavailable, not zero. LOS is a normal approximation; confidence intervals are not a repeated-check stopping rule.</p><h3>Send useful feedback</h3><p>Include <b>Engine Arena 0.2.0 Beta 2</b>, your Windows version, engine names and versions, tournament format, time control, concurrency, steps to reproduce, and what you expected versus what happened. A screenshot and a small exported PGN can help. Review attachments before sharing; reports can include local file paths and engine settings.</p><p class="caption">Extended unattended testing and clean-machine acceptance are planned after this functional review. GPU telemetry currently supports NVIDIA; CPU sensor readings need the optional signed driver and permission each session.</p></div>`);

// Give a first-time tester an action-oriented, compact welcome.
$('#empty h2').textContent='Your engine testing workspace';
$('#empty p').innerHTML='1. Add engine profiles &nbsp; · &nbsp; 2. Choose test conditions &nbsp; · &nbsp; 3. Start and compare';
$('#empty').classList.add('tester-empty');

const resultsHelp=document.createElement('button');resultsHelp.className='subtle';resultsHelp.textContent='Reading these results';$('.results-controls').append(resultsHelp);
resultsHelp.onclick=()=>modal('Reading engine test results',`<div class="tester-intro"><h3>Game results and samples</h3><p><b>Score %</b> counts a win as one point and a draw as half a point. <b>Draw %</b> counts draws among all official games. Byes affect tournament points, not game results or Elo.</p><p>With reversed colors enabled, <b>Elo, CI and LOS use completed opening pairs</b>. W–D–L updates after each game, so an unfinished pair can affect Score % before it affects Elo. Each pair is one statistical observation.</p><h3>Elo and uncertainty</h3><p><b>Δ Elo</b> describes performance against the opponents actually tested. It is not an absolute rating. Pool ratings provide a separate estimate relative to a chosen fixed reference.</p><p><b>Confidence interval (CI)</b> shows a range in Elo. Higher confidence produces a wider range. Normal intervals are approximate and can be too narrow for small samples. Conservative Hoeffding bounds require independent samples and are often much wider. They can extend to infinity.</p><p><b>LOS</b> is the normal-approximation likelihood of superiority against the comparison baseline. Changing the confidence level changes the interval, not LOS. Neither display is a guarantee about engine strength.</p><h3>Unavailable estimates and stopping</h3><p><b>—</b> means unavailable. Normal uncertainty and LOS need at least two samples with varied scores; all-identical scores cannot supply a useful variance estimate. <b>+∞ / −∞</b> means an unbounded estimate from the observed score, not a measured infinite playing strength.</p><p>These confidence intervals assume fixed sample sizes and independent observations. Repeatedly checking them is not a valid stopping rule. Use a configured SPRT for a sequential decision. Replacing an official SPRT result invalidates its inference and preserves the original evidence.</p></div>`);
